name: nostr_relay
description: Embeddable Dart Nostr relay with NIP-01, NIP-42, NIP-59 and NIP-77 support.
version: 1.0.0
repository: https://github.com/nogringo/dart-nostr-relay

topics:
  - nostr
  - relay

environment:
  sdk: ^3.12.1

dependencies:
  args: ^2.7.0
  bip340: ^0.3.1
  convert: ^3.1.2
  crypto: ^3.0.7
  sqlite3: ^3.3.1

dev_dependencies:
  lints: ^6.0.0
  ndk: ^0.8.3
  test: ^1.25.6
  web_socket_channel: ^3.0.3
